# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170818_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
